purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.9526220576371998
  brandStrength: 0.2623650429304689
  lightness: 0.1416823198087513
  brandColors:
    - '#534E4A'
    - '#121701'
    - '#ED8666'
    - '#8D7670'
    - '#CEBDB3'
  rhythmicContrast: 0.2914308973122388
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: Tekelala
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.1591025358065963
layout_spectrum: 0.8782486009877175
